import { defineObject, FieldType } from 'twenty-sdk';
import { UUIDS } from '../constants';

export default defineObject({
  universalIdentifier: UUIDS.contract.object,
  nameSingular: 'contract',
  namePlural: 'contracts',
  labelSingular: 'Contract',
  labelPlural: 'Contracts',
  description: 'Placement contracts tracking client/vendor chains, dates, and profitability',
  icon: 'IconFileText',
  labelIdentifierFieldMetadataUniversalIdentifier: UUIDS.contract.contractNumber,
  fields: [
    // -- CONTRACT-01: Core Fields --

    {
      universalIdentifier: UUIDS.contract.status,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconCircleDot',
      defaultValue: "'DRAFT'",
      options: [
        { id: UUIDS.contract.options.status.draft, value: 'DRAFT', label: 'Draft', color: 'gray', position: 0 },
        { id: UUIDS.contract.options.status.active, value: 'ACTIVE', label: 'Active', color: 'green', position: 1 },
        { id: UUIDS.contract.options.status.expired, value: 'EXPIRED', label: 'Expired', color: 'orange', position: 2 },
        { id: UUIDS.contract.options.status.terminated, value: 'TERMINATED', label: 'Terminated', color: 'red', position: 3 },
        { id: UUIDS.contract.options.status.renewed, value: 'RENEWED', label: 'Renewed', color: 'blue', position: 4 },
        { id: UUIDS.contract.options.status.onHold, value: 'ON_HOLD', label: 'On Hold', color: 'yellow', position: 5 },
      ],
    },
    {
      universalIdentifier: UUIDS.contract.contractType,
      type: FieldType.SELECT,
      name: 'contractType',
      label: 'Contract Type',
      icon: 'IconCategory',
      options: [
        { id: UUIDS.contract.options.contractType.w2, value: 'W2', label: 'W2', color: 'blue', position: 0 },
        { id: UUIDS.contract.options.contractType.c2c, value: 'C2C', label: 'C2C', color: 'green', position: 1 },
        { id: UUIDS.contract.options.contractType._1099, value: '_1099', label: '1099', color: 'purple', position: 2 },
        { id: UUIDS.contract.options.contractType.subcontract, value: 'SUBCONTRACT', label: 'Subcontract', color: 'orange', position: 3 },
        { id: UUIDS.contract.options.contractType.directHire, value: 'DIRECT_HIRE', label: 'Direct Hire', color: 'turquoise', position: 4 },
      ],
    },
    {
      universalIdentifier: UUIDS.contract.startDate,
      type: FieldType.DATE_TIME,
      name: 'startDate',
      label: 'Start Date',
      icon: 'IconCalendarEvent',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: UUIDS.contract.endDate,
      type: FieldType.DATE_TIME,
      name: 'endDate',
      label: 'End Date',
      icon: 'IconCalendarOff',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: UUIDS.contract.value,
      type: FieldType.CURRENCY,
      name: 'contractValue',
      label: 'Contract Value',
      icon: 'IconCurrencyDollar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: UUIDS.contract.renewalDate,
      type: FieldType.DATE_TIME,
      name: 'renewalDate',
      label: 'Renewal Date',
      icon: 'IconRefresh',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: UUIDS.contract.autoRenew,
      type: FieldType.BOOLEAN,
      name: 'autoRenew',
      label: 'Auto Renew',
      icon: 'IconRepeat',
      defaultValue: false,
    },
    {
      universalIdentifier: UUIDS.contract.probationEndDate,
      type: FieldType.DATE_TIME,
      name: 'probationEndDate',
      label: 'Probation End Date',
      icon: 'IconCalendarCheck',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: UUIDS.contract.noticePeriod,
      type: FieldType.NUMBER,
      name: 'noticePeriod',
      label: 'Notice Period (Days)',
      icon: 'IconAlarm',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: UUIDS.contract.contractNumber,
      type: FieldType.TEXT,
      name: 'contractNumber',
      label: 'Contract Number',
      icon: 'IconHash',
    },
    {
      universalIdentifier: UUIDS.contract.department,
      type: FieldType.TEXT,
      name: 'department',
      label: 'Department',
      icon: 'IconBuilding',
    },
    {
      universalIdentifier: UUIDS.contract.notes,
      type: FieldType.RICH_TEXT,
      name: 'contractNotes',
      label: 'Notes',
      icon: 'IconNotes',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: UUIDS.contract.documentLinks,
      type: FieldType.LINKS,
      name: 'documentLinks',
      label: 'Document Links',
      icon: 'IconPaperclip',
      isNullable: true,
      defaultValue: null,
    },

    // -- CONTRACT-02: Client Fields --

    {
      universalIdentifier: UUIDS.contract.clientName,
      type: FieldType.TEXT,
      name: 'clientName',
      label: 'Client Name',
      icon: 'IconBriefcase',
    },
    {
      universalIdentifier: UUIDS.contract.clientContactName,
      type: FieldType.TEXT,
      name: 'clientContactName',
      label: 'Client Contact Name',
      icon: 'IconUser',
    },
    {
      universalIdentifier: UUIDS.contract.clientContactEmail,
      type: FieldType.EMAILS,
      name: 'clientContactEmail',
      label: 'Client Contact Email',
      icon: 'IconMail',
    },
    {
      universalIdentifier: UUIDS.contract.clientContactPhone,
      type: FieldType.PHONES,
      name: 'clientContactPhone',
      label: 'Client Contact Phone',
      icon: 'IconPhone',
    },
    {
      universalIdentifier: UUIDS.contract.clientWorksite,
      type: FieldType.TEXT,
      name: 'clientWorksite',
      label: 'Client Worksite',
      icon: 'IconMapPin',
    },
    {
      universalIdentifier: UUIDS.contract.clientIndustry,
      type: FieldType.TEXT,
      name: 'clientIndustry',
      label: 'Client Industry',
      icon: 'IconBuildingFactory',
    },
    {
      universalIdentifier: UUIDS.contract.msaStatus,
      type: FieldType.SELECT,
      name: 'msaStatus',
      label: 'MSA Status',
      icon: 'IconFileCheck',
      options: [
        { id: UUIDS.contract.options.msaStatus.active, value: 'ACTIVE', label: 'Active', color: 'green', position: 0 },
        { id: UUIDS.contract.options.msaStatus.pending, value: 'PENDING', label: 'Pending', color: 'yellow', position: 1 },
        { id: UUIDS.contract.options.msaStatus.expired, value: 'EXPIRED', label: 'Expired', color: 'red', position: 2 },
        { id: UUIDS.contract.options.msaStatus.notApplicable, value: 'NOT_APPLICABLE', label: 'N/A', color: 'gray', position: 3 },
      ],
    },
    {
      universalIdentifier: UUIDS.contract.clientManagerName,
      type: FieldType.TEXT,
      name: 'clientManagerName',
      label: 'Client Manager Name',
      icon: 'IconUserStar',
    },
    {
      universalIdentifier: UUIDS.contract.billRate,
      type: FieldType.NUMBER,
      name: 'billRate',
      label: 'Bill Rate',
      icon: 'IconReceipt',
      isNullable: true,
      defaultValue: null,
    },

    // -- CONTRACT-03: Vendor Fields --

    {
      universalIdentifier: UUIDS.contract.vendorName,
      type: FieldType.TEXT,
      name: 'vendorName',
      label: 'Vendor Name',
      icon: 'IconTruck',
    },
    {
      universalIdentifier: UUIDS.contract.vendorContactName,
      type: FieldType.TEXT,
      name: 'vendorContactName',
      label: 'Vendor Contact Name',
      icon: 'IconUserCheck',
    },
    {
      universalIdentifier: UUIDS.contract.vendorContactEmail,
      type: FieldType.EMAILS,
      name: 'vendorContactEmail',
      label: 'Vendor Contact Email',
      icon: 'IconMailForward',
    },
    {
      universalIdentifier: UUIDS.contract.vendorPaymentTerms,
      type: FieldType.TEXT,
      name: 'vendorPaymentTerms',
      label: 'Vendor Payment Terms',
      icon: 'IconCalendarDollar',
    },
    {
      universalIdentifier: UUIDS.contract.vendorMargin,
      type: FieldType.NUMBER,
      name: 'vendorMargin',
      label: 'Vendor Margin',
      icon: 'IconPercentage',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: UUIDS.contract.vendorContractStatus,
      type: FieldType.SELECT,
      name: 'vendorContractStatus',
      label: 'Vendor Contract Status',
      icon: 'IconClipboardCheck',
      options: [
        { id: UUIDS.contract.options.vendorContractStatus.active, value: 'ACTIVE', label: 'Active', color: 'green', position: 0 },
        { id: UUIDS.contract.options.vendorContractStatus.pending, value: 'PENDING', label: 'Pending', color: 'yellow', position: 1 },
        { id: UUIDS.contract.options.vendorContractStatus.expired, value: 'EXPIRED', label: 'Expired', color: 'red', position: 2 },
        { id: UUIDS.contract.options.vendorContractStatus.terminated, value: 'TERMINATED', label: 'Terminated', color: 'orange', position: 3 },
      ],
    },

    // -- CONTRACT-04: Placement Fields --

    {
      universalIdentifier: UUIDS.contract.placementChain,
      type: FieldType.TEXT,
      name: 'placementChain',
      label: 'Placement Chain',
      description: 'The placement chain, e.g. "You -> Vendor -> Client"',
      icon: 'IconArrowsRight',
    },
    {
      universalIdentifier: UUIDS.contract.placementStartDate,
      type: FieldType.DATE_TIME,
      name: 'placementStartDate',
      label: 'Placement Start Date',
      icon: 'IconPlayerPlay',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: UUIDS.contract.placementEndDate,
      type: FieldType.DATE_TIME,
      name: 'placementEndDate',
      label: 'Placement End Date',
      icon: 'IconPlayerStop',
      isNullable: true,
      defaultValue: null,
    },

    // -- CONTRACT-05: Profitability Fields --

    {
      universalIdentifier: UUIDS.contract.consultantPayRate,
      type: FieldType.NUMBER,
      name: 'consultantPayRate',
      label: 'Consultant Pay Rate',
      icon: 'IconWallet',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: UUIDS.contract.yourMargin,
      type: FieldType.NUMBER,
      name: 'yourMargin',
      label: 'Your Margin',
      icon: 'IconTrendingUp',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: UUIDS.contract.rateType,
      type: FieldType.SELECT,
      name: 'rateType',
      label: 'Rate Type',
      icon: 'IconClock',
      defaultValue: "'HOURLY'",
      options: [
        { id: UUIDS.contract.options.rateType.hourly, value: 'HOURLY', label: 'Hourly', color: 'blue', position: 0 },
        { id: UUIDS.contract.options.rateType.annual, value: 'ANNUAL', label: 'Annual', color: 'green', position: 1 },
        { id: UUIDS.contract.options.rateType.fixed, value: 'FIXED', label: 'Fixed', color: 'purple', position: 2 },
      ],
    },
  ],
});
